apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-cert-test
  namespace: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: devkubernetes.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx-controller
            port:
              number: 80

  - host: devtrino.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx-controller
            port:
              number: 80

  tls:
  - hosts:
    - devkubernetes.duckdns.org
    - devtrino.duckdns.org
    secretName: dev-cert-test-tls