apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-v3-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: devkubernetes.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dummy-backend
            port:
              number: 80
  tls:
  - hosts:
    - devkubernetes.duckdns.org
    secretName: dev-cert-test-tls