apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-v3-ingress
  namespace: ingress-nginx
  annotations:
    # This triggers cert-manager to issue the cert automatically
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Set to true once certs work
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: ingress-nginx # Replaces the old annotation
  rules:
    - host: devkubernetes.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-kubernetes-service
                port:
                  number: 80
    - host: devtrino.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-trino-service
                port:
                  number: 80
  tls:
    - hosts:
        - devkubernetes.duckdns.org
        - devtrino.duckdns.org
      # Ensure this matches the secretName in your Certificate object
      secretName: dev-cert-test-tls